### ISSUE TITLE
gomail with go1.8 crashed!

### ISSUE THREAD

**Issue by toplinuxsir** [go-gomail/gomail#76]
when call DialAndSend

goroutine 575 [IO wait]:
net.runtime_pollWait(0x7f58d41d8430, 0x72, 0x18)
	/home/lhs/soft/go/go1.8.0/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4205775d8, 0x72, 0x10eb5c0, 0x10e68c0)
	/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4205775d8, 0xc420677c00, 0x400)
	/home/lhs/soft/go/go1.8.0/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420577570, 0xc420677c00, 0x400, 0x400, 0x0, 0x10eb5c0, 0x10e68c0)
	/home/lhs/soft/go/go1.8.0/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc420206e88, 0xc420677c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/home/lhs/soft/go/go1.8.0/go/src/net/net.go:181 +0x70
crypto/tls.(*block).readFromUntil(0xc420462e10, 0x7f58d41d9030, 0xc420206e88, 0x5, 0xc420206e88, 0x10)
	/home/lhs/soft/go/go1.8.0/go/src/crypto/tls/conn.go:488 +0x98
crypto/tls.(*Conn).readRecord(0xc4205a0e00, 0xbdaf17, 0xc4205a0f20, 0xc4206f4000)
	/home/lhs/soft/go/go1.8.0/go/src/crypto/tls/conn.go:590 +0xc4
crypto/tls.(*Conn).Read(0xc4205a0e00, 0xc420a42000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/lhs/soft/go/go1.8.0/go/src/crypto/tls/conn.go:1134 +0x11d
bufio.(*Reader).fill(0xc42045f380)
	/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadSlice(0xc42045f380, 0xc42002480a, 0xc420764e10, 0xc4205d1820, 0xc4205a1018, 0xc420462de0, 0xbd8ea0)
	/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:338 +0xbb
bufio.(*Reader).ReadLine(0xc42045f380, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4205d1898)
	/home/lhs/soft/go/go1.8.0/go/src/bufio/bufio.go:367 +0x37
net/textproto.(*Reader).readLineSlice(0xc420358630, 0xc4fffffffe, 0x0, 0xc2b, 0x3d5, 0xc2b)
	/home/lhs/soft/go/go1.8.0/go/src/net/textproto/reader.go:55 +0x5f
net/textproto.(*Reader).ReadLine(0xc420358630, 0x0, 0x0, 0xffffffffffffffff, 0x0)
	/home/lhs/soft/go/go1.8.0/go/src/net/textproto/reader.go:36 +0x2f
net/textproto.(*Reader).readCodeLine(0xc420358630, 0xfa, 0xc2b, 0x0, 0x0, 0xc2b, 0x0, 0x0)
	/home/lhs/soft/go/go1.8.0/go/src/net/textproto/reader.go:177 +0x2f
net/textproto.(*Reader).ReadResponse(0xc420358630, 0xfa, 0x0, 0x9e3fbd, 0xc42045fb00, 0xc4209fa000, 0xc42045fb00)
	/home/lhs/soft/go/go1.8.0/go/src/net/textproto/reader.go:255 +0x4d
net/smtp.(*dataCloser).Close(0xc420a3bca0, 0x7f58d41e9780, 0xc420a3bca0)
	/home/lhs/soft/go/go1.8.0/go/src/net/smtp/smtp.go:268 +0x53
gopkg.in/gomail%2ev2.(*smtpSender).Send(0xc420a3b620, 0xc420a3b6a0, 0x11, 0xc420358870, 0x5, 0x9, 0x10e8900, 0xc4209fa000, 0x2000000000000, 0x15)
	/home/lhs/soft/go/go1.8.0/gopath/src/gopkg.in/gomail.v2/smtp.go:176 +0x3fd
gopkg.in/gomail%2ev2.send(0x7f58d40b2520, 0xc420a3b620, 0xc4209fa000, 0xc42031c000, 0x7f58d40b2520)
	/home/lhs/soft/go/go1.8.0/gopath/src/gopkg.in/gomail.v2/send.go:57 +0xdc
gopkg.in/gomail%2ev2.Send(0x7f58d40b2520, 0xc420a3b620, 0xc4205d1cf0, 0x1, 0x1, 0x180, 0xb98ec0)
	/home/lhs/soft/go/go1.8.0/gopath/src/gopkg.in/gomail.v2/send.go:38 +0x7a
gopkg.in/gomail%2ev2.(*Dialer).DialAndSend(0xc420577500, 0xc4202c1cf0, 0x1, 0x1, 0x0, 0x0)
	/home/lhs/soft/go/go1.8.0/gopath/src/gopkg.in/gomail.v2/smtp.go:137 +0xe9

**Comment by u007** [comment]
which version 2? mine seems to be working on 
go version go1.8 darwin/amd64

**Comment by aletheia7** [comment]
Works fine.

Version: go version go1.8.3 linux/amd64
